### ISSUE TITLE
[Idea] Move all BStats-Stuff to GitHub Organisation?

### ISSUE THREAD

**Issue by Andre601** [Bastian/bStats#137] opened 2021-03-16 11:06 UTC
This is something I believe would be a good idea to do.
You have so many repos related to BStats that it sure could be beneficial to have it organized into a GitHub organization.

And as long as you wouldn't create a new repo with the same name as the one you moved would a redirect exist that goes to the new location, so you don't have to fear about old links pointing to a 404 page.

A possible name to use for the org could be bstats-org since bstats is taken already.

This of course is a small idea, but considering bstats has become something rather big would it be better to perhaps move the stuff to a dedicated org for having it organized.

Another thing I want to suggest here to, if that would become a thing, is to actually link the org on the bstats website, so that people can actually find it.
It's always a struggle for me to find this or the bstats-metrics repository, so having a link on the site itself could help a lot.
If no org would be used, then perhaps add a link to this repo at least?

**Comment by Bastian** [comment] 2021-03-16 18:34
Thank you for the suggestion!

It would indeed be cleaner to group all the repositories in an organization and I've already played with this thought myself. However, there's a simple reason why I've decided against it. This might sound super selfish and maybe even a bit stupid: From my experience, you get a lot more attention (and followers) if you have popular repositories on your own GitHub account compared to maintaining one in an organization. As my GitHub profile is an important part of my portfolio as a software developer (both for future job applications and maybe some freelance work), I would like to keep the repositories on my private GitHub account.

Regarding the link to the repo: There's already a link in the Footer of the [new design](https://test.bstats.org/services/1):
![image](https://user-images.githubusercontent.com/5033001/111360585-34d7ca00-868d-11eb-95e1-02c0841498fd.png)
The problem here is ofc that there is more than a single repository: There's one for the (new) [frontend](https://github.com/Bastian/bstats-web), one for the (new) [backend](https://github.com/Bastian/bstats-backend), one for the [Metrics classes](https://github.com/Bastian/bStats-Metrics), and [this one](https://github.com/Bastian/bStats). I'm not sure to which of these the link should go. Maybe it could also go to a second page that lists all of the repository. But an extra page just to list the repository might be a bit of an overkill.

**Comment by Andre601** [comment] 2021-03-17 03:51
Understandable.

Also, I didn't know about the redesign and it looks nice (finally dark theme!)

**Comment by Andre601** [comment] 2021-03-17 03:54
Also, maybe have a GitHub text that, when clicked on, will expand and reveal the links.

**Comment by Andre601** [comment] 2021-04-13 10:02
Something I wonder and ask here now, since the new design was mentioned:
Will it be possible to see specific statistics for specific Plugin versions? Like when I want to see stats that v1.1 of my plugin send, could I filter out any stats send by v1.0?

Another thing that hopefully gets some minor improvement is the way you can see certain parts in a graph.
Right now does it seem like that Pie Charts won't display the name of all pieces when there are too many of them(?)
See this image for what I mean (Taken from PlaceholderAPI bStats):
![image](https://user-images.githubusercontent.com/11576465/114535070-f44d7b00-9c4f-11eb-9e1b-e1e202091e58.png)

**Comment by Bastian** [comment] 2021-04-13 16:05
> Will it be possible to see specific statistics for specific Plugin versions? Like when I want to see stats that v1.1 of my plugin send, could I filter out any stats send by v1.0?

No. This is something that the current backend and database layout does not support. I might look into it once I'm done with the current rewrite, but considering that this will very likely require **a lot** more ressources, I doubt that bStats will ever support at – or maybe only as as a payed "premium" feature.

> Another thing that hopefully gets some minor improvement is the way you can see certain parts in a graph.
Right now does it seem like that Pie Charts won't display the name of all pieces when there are too many of them(?)
See this image for what I mean (Taken from PlaceholderAPI bStats):

I'm open for suggestions on how to implement it. The [current implementation of the new frontend](https://github.com/Bastian/bstats-web/blob/dc08c5b0a32400ed772404da2a06241566a5bf91/src/components/charts/PieChart.svelte#L17-L25) shows the 9 largest slices and groups everything left in the "Other" category. We can probably discuss if the limit should be increased, but at some point there must be a cut because having a pie with 50+ slices is just not an option.

Fyi: The complete data is available via the REST api: https://bstats.org/api/v1/plugins/438/charts/expansions_used/data

**Comment by Bastian** [comment] 2021-04-13 16:06
I'm also going to close this issue as its initial suggestion has been answered. Feel free to answer to my comment above (I will still read it even if the issue is closed) or just open a new issue specific to one of the two topics.

**Closed by Bastian** 2021-04-13 16:06 UTC

**Comment by Andre601** [comment] 2021-04-13 16:22
> I'm open for suggestions on how to implement it. The [current implementation of the new frontend](https://github.com/Bastian/bstats-web/blob/dc08c5b0a32400ed772404da2a06241566a5bf91/src/components/charts/PieChart.svelte#L17-L25) shows the 9 largest slices and groups everything left in the "Other" category. We can probably discuss if the limit should be increased, but at some point there must be a cut because having a pie with 50+ slices is just not an option.

Would the pie in such a case be of type drilldown? It would be somewhat logical to perhaps have the "other" tab expand when clicked on to then reveal more data/info.

Something I btw noticed in the test page, but can't tell if it's just because of it being a test or intentional or whatever, is that for BungeeCord global stats, there seems to be no brand/type chart telling you how many proxies are waterfall, how many bungeecord, and so on. Is the retrieval of this data more difficult?

And another minor thing I noticed and that should be put into the "clean up" to do at most, is that the global stats for velocity and bungee should perhaps say "Proxies" and not "Servers", since that could get confused with actual servers, which are listed under the "Managed Servers" section itself. Just a small thing tho.

**Comment by Bastian** [comment] 2021-04-13 16:34
> Would the pie in such a case be of type drilldown? It would be somewhat logical to perhaps have the "other" tab expand when clicked on to then reveal more data/info.

Sounds like a good solution (at least for normal pie charts). This could even be nested for pie with very large amounts of data.

> Something I btw noticed in the test page, but can't tell if it's just because of it being a test or intentional or whatever, is that for BungeeCord global stats, there seems to be no brand/type chart telling you how many proxies are waterfall, how many bungeecord, and so on. Is the retrieval of this data more difficult?

Maybe I am blind, but isn't this data also not available on the current/"old" frontend? As far as I can see, the backend does not parse this information currently. I'm not even sure, if it is sent by the Metrics classes.
Is this information included in the string from [`getProxy().getVersion()`](https://github.com/Bastian/bStats-Metrics/blob/a80a31a59e3fa6670899939fffdbdaacd401b7f1/bungeecord/src/main/java/org/bstats/bungeecord/Metrics.java#L118)? If yes, would you mind open an issue in the [bstats-backend](https://github.com/Bastian/bstats-backend) repository about it? Because if it is included, it's just a matter of parsing it in the backend.

> And another minor thing I noticed and that should be put into the "clean up" to do at most, is that the global stats for velocity and bungee should perhaps say "Proxies" and not "Servers", since that could get confused with actual servers, which are listed under the "Managed Servers" section itself. Just a small thing tho.

Sure. I've created an issue for it (https://github.com/Bastian/bstats-web/issues/1).

**Comment by Andre601** [comment] 2021-04-13 16:53
> Maybe I am blind, but isn't this data also not available on the current/"old" frontend? As far as I can see, the backend does not parse this information currently. I'm not even sure, if it is sent by the Metrics classes.
> Is this information included in the string from [`getProxy().getVersion()`](https://github.com/Bastian/bStats-Metrics/blob/a80a31a59e3fa6670899939fffdbdaacd401b7f1/bungeecord/src/main/java/org/bstats/bungeecord/Metrics.java#L118)? If yes, would you mind open an issue in the [bstats-backend](https://github.com/Bastian/bstats-backend) repository about it? Because if it is included, it's just a matter of parsing it in the backend.

Seems to only return the info of the implementation version.
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L534-L538

I assumed you did a different trick to get the current implementation like checking specific class paths or similar. So my bad there.

**Comment by Andre601** [comment] 2022-01-30 20:05
Yo. Any updates on the progress of the new design?

Just curious to know what the overall status of the site is so far and if there would be stuff I (or other people) could help with.

**Comment by Bastian** [comment] 2022-02-08 17:45
No, sorry. No new updates.
With university + work + life in general, I don't have time to work on it at the moment.
