### ISSUE TITLE
[Idea] Add Spigot / Bungee

### ISSUE THREAD

**Issue by KarmaConfigs** [Bastian/bStats#113] opened 2020-02-16 01:42 UTC
I would like to see an option to do this, due I want to create simple pie like "Spigot or Bungee" or "Locale on Bungee" and "Locale on Spigot" in the same metrics page, It is very tiring to have to change pages to see how the state of each metric is going

**Comment by MiniDigger** [comment] 2020-02-18 10:11
duplicate of #9, #21 and #38

**Comment by Bastian** [comment] 2020-03-04 19:54
Hi,

thank you for your idea, but for various reasons I cannot add a universal plugin type.

**Closed by Bastian** 2020-03-04 19:54 UTC

**Comment by Bastian** [comment] 2020-03-04 19:57
See https://bstats.org/faq :-)
