### ISSUE TITLE
Filtering: Limit other graphs to selection in one graph

### ISSUE THREAD

**Issue by MiniDigger** [Bastian/bStats#74] opened 2018-07-30 13:50 UTC
The title isn't very clear so here an example:
when I want to analyze if its worth dropping java 7 support I want to know the impact. bStats allows me to see how many of my servers use java 7, but I don't know how many players would be affected. what would be cool is if I select java 7 in the java version graph that the other graphs would update to only show stats for the servers that match my filter: having java version = 7.
The same could also be helpful for MC Version, when trying to find out where to best place a server to do backend calculation (want to place as close as possible to big servers), OS (if its worth maintaining windows hacks) and similar stuff.

**Comment by Bastian** [comment] 2018-08-01 16:19
Thank you for the suggestion. This would be a nice feature, but I'm not sure if it will ever be implemented.
See my answer in https://github.com/Bastian/bStats/issues/50

I'll close this issue, as it's a duplicate of the issue I linked above.

**Closed by Bastian** 2018-08-01 16:19 UTC
